version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/andela-football-league
    command: >
      sh -c "python manage.py runserver"
    environment:
      - DB_HOST=db
      - DB_NAME=andela-football-league
      - DB_USER=postgres
      - DB_PASS=""
      - DB_PORT=5432
    depends_on:
      - db
  
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=andela-football-league
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""